version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: veterinary-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - veterinary-network

  backend:
    build: ./backend
    container_name: veterinary-backend
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/veterinary
      - PORT=3000
    depends_on:
      - mongodb
    networks:
      - veterinary-network

  frontend:
    build: ./frontend
    container_name: veterinary-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:3000
    depends_on:
      - backend
    networks:
      - veterinary-network

networks:
  veterinary-network:
    driver: bridge

volumes:
  mongodb_data:
