version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "8080:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:3000
    networks:
      - videojuegos-network

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://root:password@base_datos:27017/test?authSource=admin
    depends_on:
      - base_datos
    networks:
      - videojuegos-network

  base_datos:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
    networks:
      - videojuegos-network

networks:
  videojuegos-network:
    driver: bridge

volumes:
  mongo-data: